---
- name: Install Node
  dnf:
    name: "@nodejs:18"
    update_cache: yes
- name: Copy server files
  copy:
    src: ../../../../server/{{ item }}
    dest: /home/opc/server/
    owner: opc
  with_items:
    - "index.js"
    - "package.json"
    - "package-lock.json"
- name: Install dependencies
  command: npm install
  become: true
  become_user: opc
  args:
    chdir: /home/opc/server/
- name: Add firewall port
  firewalld:
    zone: public
    port: 3000/tcp
    permanent: yes
    immediate: yes
    state: enabled
- name: Install pm2
  command: npm install pm2 -g
- name: Run Server App
  command: pm2 -f start index.js
  become: true
  become_user: opc
  args:
    chdir: /home/opc/server/